### PR TITLE
Update baseline

### PR DESCRIPTION
**Pull request by danog**
Required by https://github.com/vimeo/psalm/pull/8525

### CODE REVIEW

**Comment by orklah** [comment]
Hey @weirdan! Do you have permissions here? I can't merge or approve workflow

**Comment by weirdan** [comment]
> Do you have permissions here?

I do, and now you have them too.

**Comment by orklah** [comment]
Thanks!

@danog seems like there are failures on items this PR removes from the baseline

Settings differences maybe?

**Comment by danog** [comment]
Yep, it's probably that, locally I just had the two issues present in the immutable PR + a few other issues caused by the absence of the SOAP extension

**Comment by danog** [comment]
Ah nono wait it's simply because the psalm tests are running using the old version of psalm, not the new immutable one

**Comment by danog** [comment]
OK I installed php-soap and re-generated the baseline with the new immutable version of psalm, then re-ran analysis with the old version and got the following issues:

* A redundant class-string assertion, which is fixed in the new version
```
ERROR: RedundantConditionGivenDocblockType - src/Framework/MockObject/Generator.php:1038:13 - Docblock-defined type class-string for $type is always class-string (see https://psalm.dev/156)
            assert(class_exists($type));
```

* This error is still present in the new version, only now it's an `InvalidPropertyAssignmentValue`
```
ERROR: PropertyTypeCoercion - src/Logging/TestDox/TestMethodCollector.php:161:13 - $this->tests expects 'array<class-string, array{duration: PHPUnit\Event\Telemetry\Duration, status: PHPUnit\Framework\TestStatus\TestStatus, test: PHPUnit\Event\Code\TestMethod}>',  parent type 'non-empty-array<class-string, array{duration?: PHPUnit\Event\Telemetry\Duration, status?: PHPUnit\Framework\TestStatus\TestStatus, test?: PHPUnit\Event\Code\TestMethod}>' provided (see https://psalm.dev/198)
            $this->tests[$test->className()] = [];
```

* This error is still present in the new version, only now it's an `ArgumentTypeCoercion`
```
ERROR: InvalidArgument - src/TextUI/Command/Commands/ListTestsAsTextCommand.php:35:48 - Argument 1 of RecursiveIteratorIterator::__construct expects IteratorAggregate|RecursiveIterator, but Traversable<mixed, mixed>&Iterator provided (see https://psalm.dev/004)
        foreach (new RecursiveIteratorIterator($this->suite->getIterator()) as $test) {
```

* This error is still present in the new version, only now it's an `ArgumentTypeCoercion`
```
ERROR: InvalidArgument - src/TextUI/Command/Commands/ListTestsAsXmlCommand.php:45:48 - Argument 1 of RecursiveIteratorIterator::__construct expects IteratorAggregate|RecursiveIterator, but Traversable<mixed, mixed>&Iterator provided (see https://psalm.dev/004)
        foreach (new RecursiveIteratorIterator($this->suite->getIterator()) as $test) {
```

I think this can be merged before/after merging the immutable PR in psalm.

**Pull request closed without merging**
